131
practice-uffs/app-practice pull request #141
Opened 2021-07-22 13:43 UTC by stefanimeneghetti

Fix: #131

2021-07-28 13:55 UTC, Dovyski requested changes
A implementação maravilhosa. Os comentários que eu fiz são para deixar a lógica mais fácil de ser entendida e do código ser mantido no futuro.

Também fiz alguns comentários sobre formatação.

2021-07-28 13:55 UTC, Dovyski commented on src/js/storage.js
> +  partialCleaning: () => {
Eu evitaria métodos com nome no gerúndio, tipo `ing`. Então um nome melhor seria `partialClear()` ou `parcialClean()`. Julgando pela implementação do método, eu acho até que um nome melhor seria `removeAllButUserData()`.

2021-07-28 13:55 UTC, Dovyski commented on src/js/storage.js
> +          if (settings.offlineStorage)
Eu acho que ifs sem chaves, mesmo que eles tenham um único comando, são mais propensos a bugs. Acho que seria legal evitar:

```js
if () 
  algo();
```

em favor de:

```js
if () {
  algo();
}
```

2021-07-28 13:55 UTC, Dovyski commented on src/js/storage.js
> +    if (service)
`if () { ... }`

2021-07-28 13:55 UTC, Dovyski commented on src/js/storage.js
> +          if (settings.offlineStorage && !service.error)
`if ( ) { ... }`

2021-07-28 13:55 UTC, Dovyski commented on src/pages/service-details.f7.html
> +            if (!service.error)
Usando a ideia de "sair do fluxo antes", eu refatoraria isso da seguinte forma (reduz aninhamentos e facilita o entendimento da lógica):

```
if (service.error) {
    throw service.error;  // <-- acho que tinha faltando o `service.` aqui?
}

self.$setState({
    service: service,
});
```

2021-07-28 13:55 UTC, Dovyski commented on src/pages/service-details.f7.html
> +            if (!comments.error)
Ver comentário acima sobre "sair do fluxo antes".

2021-07-28 13:55 UTC, Dovyski commented on src/pages/settings.f7.html
> +        else if(e.target.name === 'offlineStorage'){
Usar `} else if (  ) {`

2021-07-30 16:56 UTC, stefanimeneghetti commented
Corrigi os pontos solicitados e também já resolvi o conflito que havia com a branch dev.

2021-07-30 17:53 UTC, Dovyski commented
Obrigado, @stefanimeneghetti ! Só o @CleissonVieira dar uma última olhada e fazer o merge.

2021-08-02 17:49 UTC, merged