feat: adiciona plugin para gerar token fcm e o salva no banco de dados por meio da api
practice-uffs/app-practice pull request #144
Opened 2021-07-29 21:53 UTC by stefanimeneghetti

Para gerar o apk com o plugin do fcm adicionado é necessario:
1. Garantir que a linha `<widget id="cc.uffs.practice" version="0.4.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">` do arquivo `config.xml` possua o id **igual** ao nome do pacote criado no firebase.
2. Caso o pacote criado possua um nome diferente do que esta previamente configurado no arquivo `config.xml` é necessario remover e readicionar a plataforma android por meio do cordova.
3. Adicionar o arquivo `google-services.json` gerado pelo firebase à pasta `/cordova/platforms/android/app/src/google-services.json`

Fix: #135

2021-07-30 11:34 UTC, Dovyski requested changes
A implementação está excelente, só vi uma coisa diferente ali (3 chamadas seguidas) que não sei se está certo.

2021-07-30 11:34 UTC, Dovyski commented on src/js/storage.js
> +        storage.setFcmToken(token);
Porque existem 3 chamadas a `storage.setFcmToken(token);` aqui? Isso é o esperado?

2021-07-30 11:34 UTC, Dovyski commented on src/pages/settings.f7.html
> +        else if (e.target.name === 'allowNotifications') {
`} else if () {`

2021-07-30 11:35 UTC, Dovyski commented
Excelente! Sobre essas instruções para gerar o APK, por favor, coloca elas na seção de build do README (se não tiver uma seção assim, crie ela). Não precisa fazer pull request para isso, pode editar o README direto na dev.

2021-07-30 16:12 UTC, stefanimeneghetti commented
Mudanças solicitadas feitas, quanto a parte que a função estava sendo chamada 3 vezes eu não tinha visto isso então removi duas das chamadas.

2021-08-04 03:44 UTC, CleissonVieira commented
@stefanimeneghetti surgiram conflitos hehe poderia, por gentileza, resolver e me marcar para nova revisão?

2021-08-04 11:06 UTC, stefanimeneghetti commented
@CleissonVieira Conflitos corrigidos.

2021-08-04 12:44 UTC, merged